import type { LocalizationStrings } from "./en";

export const am: LocalizationStrings = {
  locale: "am",
  today: "ዛሬ",
  cancel: "ይቅር",
  confirm: "አረጋግጥ",
  selectDate: "ቀን ይምረጡ",
  year: "ዓመት",
  month: "ወር",
  previousMonth: "ያለፈው ወር",
  nextMonth: "ቀጣዩ ወር",
  previousYear: "ያለፈው ዓመት",
  nextYear: "ቀጣዩ ዓመት",
  months: [
    "መስከረም",
    "ጥቅምት",
    "ኅዳር",
    "ታኅሣሥ",
    "ጥር",
    "የካቲት",
    "መጋቢት",
    "ሚያዝያ",
    "ግንቦት",
    "ሰኔ",
    "ሐምሌ",
    "ነሐሴ",
    "ጳጉሜን",
  ],
  shortMonths: [
    "መስ",
    "ጥቅ",
    "ኅዳ",
    "ታኅ",
    "ጥር",
    "የካ",
    "መጋ",
    "ሚያ",
    "ግን",
    "ሰኔ",
    "ሐም",
    "ነሐ",
    "ጳጉ",
  ],
  weekdays: [
    "እሑድ",
    "ሰኞ",
    "ማክሰኞ",
    "ረቡዕ",
    "ሐሙስ",
    "ዓርብ",
    "ቅዳሜ",
  ],
  shortWeekdays: ["እሑ", "ሰኞ", "ማክ", "ረቡ", "ሐሙ", "ዓር", "ቅዳ"],
};
