export const en = {
  locale: "en" as const,
  today: "Today",
  cancel: "Cancel",
  confirm: "Confirm",
  selectDate: "Select Date",
  year: "Year",
  month: "Month",
  previousMonth: "Previous Month",
  nextMonth: "Next Month",
  previousYear: "Previous Year",
  nextYear: "Next Year",
  months: [
    "Meskerem",
    "Tikimt",
    "Hidar",
    "Tahsas",
    "Tir",
    "Yekatit",
    "Megabit",
    "Miazia",
    "Ginbot",
    "Sene",
    "Hamle",
    "Nehase",
    "Pagumen",
  ],
  shortMonths: [
    "Mes",
    "Tik",
    "Hid",
    "Tah",
    "Tir",
    "Yek",
    "Meg",
    "Mia",
    "Gin",
    "Sen",
    "Ham",
    "Neh",
    "Pag",
  ],
  weekdays: [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ],
  shortWeekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
};

export type LocalizationStrings = typeof en;
